### ISSUE TITLE
Connect G360DAOio repository to Fleek and www.g360dao.io (7-10-2022)

### ISSUE THREAD

**Issue by G360DAO** [G360DAO/community#4]

**Comment by daozedong** [comment]
* Set up "g360dao.io" domain in Cloudflare to enable "@" (root) CNAME records to point to Fleek
* Set up "g360dao.io" and "www.g360dao.io" in Fleek to point to GitHub deployments
* Created DNS links in Fleek for "g360dao.io" and "www.g360dao.io"
* Created CNAME records in Cloudflare for "g360dao.io" and "www.g360dao.io" to point to Fleek
* Set up "web3.", "investors." and "whitepaper." subdomains for "g360dao.io" in GitBook
* Set up redirects in Google Domains for ".", "www.", "web3.", "investors." and "whitepaper." subdomains for "guardian360.io" to redirect to their "g360dao.io" equivalent
* Restored nameservers for "guardian360.io" from Cloudflare to Google Domains in order to enable URL redirects (guardian360.io => g360dao.io)

Nameservers, DNS records and SSL certificate creation will take up to 24 hours to propagate. Will start clean up after verification tomorrow.

**Comment by daozedong** [comment]
Everything is working correctly, have done the follow cleanup and last steps:

* Updated Discord official-links
* Removed guardian360.io from Cloudflare environment as we are back to using Google Domains for this domain
* Removed guardian360.io from Fleek as we are using redirects to g360dao.io now in Google Domains
